 version: '3'

 services:
  database:
    image: postgres
    container_name: postgres_sse
    restart: always
    ports:
      - 5432:5432

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata

  redis:
    image: redis:alpine
    container_name: redis_sse
    hostname: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: 'redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}'